### ISSUE TITLE
Template status not updated in ERPNext.

### ISSUE THREAD

**Issue by ajiragroup** [shridarpatil/frappe_whatsapp#103]
I created some templates. Only a few of them were approved. Rest are all PENDING. I checked Meta Whatsapp Business Manger, those templates are approved and active. But their status are not updated in ERPNext (Frappe_Whatsapp).
![image](https://github.com/user-attachments/assets/1faf745e-ed2e-4c31-8a87-a7dbf97c4fae)
![image](https://github.com/user-attachments/assets/3043cc79-2955-43d9-836f-e6dac24a5fb5)

**Comment by shridarpatil** [comment]
You have to set webhook to receive updates

**Comment by ajiragroup** [comment]
I am not talking about webhooks. After creating templates, most of them are still shown "PENDING" while only a few are shown "APPROVED". But WABA shows those templates as "Active", which must be approved. 
![image](https://github.com/user-attachments/assets/e8d03662-588d-4a4e-b2c3-171f48fcd095)
WABA shows all PENDING are active.
![image](https://github.com/user-attachments/assets/1413d4a0-c22e-4478-b6d1-a2ef8c089ff9)

**Comment by shridarpatil** [comment]
The pending once might have got approved later. If you setup web hook it will update the status whenever it changes on meta
