### ISSUE TITLE
Field name mobile_no does not exists

### ISSUE THREAD

**Issue by eduromanc** [shridarpatil/frappe_whatsapp#12]
Hi Dear,

I install this version, but I put the field to conect the numer, the app say this field dont exist.
Do any have any idea about this error?

![image](https://user-images.githubusercontent.com/69904374/217688898-cdffdb32-235e-4c23-9b4e-e62e34b733a1.png)

system information
![image](https://user-images.githubusercontent.com/69904374/217689249-efb610c6-253e-4ef8-9a32-a737a0ec7426.png)

**Comment by shridarpatil** [comment]
The DocType which you have selected has mobile_no field?

**Comment by eduromanc** [comment]
Sales invoice

**Comment by shridarpatil** [comment]
You need to select filed which has mobile number.

**Comment by shridarpatil** [comment]
Feel free to reopen if your still facing a problem
