### ISSUE TITLE
The Reference Document Type doesn't accept Customize Form.

### ISSUE THREAD

**Issue by elmerchanquin** [shridarpatil/frappe_whatsapp#13]
I installed Healthcare app, and by default it doesn't have any phone number field on the Patient Appointment DocType, so I created a Custom Form but on the Whatsapp Notification Reference Document Type Field it only accepts the Original DocType. At the moment I have found that is possible to fix this adding a Client Script but I think it is possible to implement this option by default.
![image](https://user-images.githubusercontent.com/31196079/218943294-e326b5de-f897-4a00-b974-3fce02d48ece.png)
![image](https://user-images.githubusercontent.com/31196079/218943388-0f502e00-76e9-42ce-bcb5-cf3079a8e54d.png)
![image](https://user-images.githubusercontent.com/31196079/218943495-dd2ce875-298e-47c4-8936-0435e16c44bd.png)

**Comment by shridarpatil** [comment]
Currently, we fetch fields by `frappe.get_doc("DocType", self.reference_doctype).fields` looks like this doesn't return custom fields. Will debug this and add a fix. Thanks

**Comment by shridarpatil** [comment]
Have pushed a patch for this.
