### ISSUE TITLE
Issues with Whatsapp notifications

### ISSUE THREAD

**Issue by elmerchanquin** [shridarpatil/frappe_whatsapp#16]
Hi, I have fixed the grammar of your message without changing the images:

Hi, I have finished all the setup process.

I have created a permanent token as per the meta docs.
I have used the URL that I saw in the picture in the readme.md, which is https://graph.facebook.com/.
I have used both versions V15.0 and V16.0, but now I am using V16.0 because the webhook is configured with that one.
I have set the phone number and business ID.
I have also set the webhook verify token.

![Screenshot 2023-03-08 090202](https://user-images.githubusercontent.com/31196079/223748913-e80ac07d-403d-4bd5-a882-4de2018f6f4c.png)

In the message list, I made many tests and found that when I send a message without receiving the first one from the number I'm messaging, the other number won't receive it. Basically, it should be a user-initiated conversation to be able to receive messages sent from the WhatsApp message functionality.

![Screenshot 2023-03-08 091149](https://user-images.githubusercontent.com/31196079/223751899-855b2e3a-38ec-4d80-8eb7-ef06b2997238.png)

So I thought that in order to create a business-initiated conversation, I should use WhatsApp templates. I created my templates, and all were approved. Then, I added them to a WhatsApp notification using the new option to set a custom field on the mobile_no field.

I had no errors in the process, but it won't send WhatsApp messages. I tried sending the message first from the user and then performing the action to receive the notification, but nothing happened. I tried with different fields and still had the issue.

Is there an additional configuration that I need to do to be able to initiate business conversations? Or any meta documentation that I need to check? Additionally, is there any way that I can check the logs generated by this app? I tried looking in the error log, but I found nothing.

"erpnext": "14.18.0",
	"frappe": "14.26.4",
	"frappe_whatsapp": "0.0.1",
	"healthcare": "15.0.0-dev",
	"hrms": "14.1.0",
	"payments": "0.0.1"
Host frappecloud

Thank you for tanking the time to read this and work on this project.

**Comment by shridarpatil** [comment]
This app currently supports only v15 can you change it to v15 and try?

**Comment by elmerchanquin** [comment]
Now is working with V15.0.
![Screenshot 2023-03-08 213639](https://user-images.githubusercontent.com/31196079/223910478-bd29d579-b42f-4b8e-8d83-b86e510776da.png)
But notifications don't work, even though I tested them with a similar configuration as the documentation.
![image](https://user-images.githubusercontent.com/31196079/223910716-97cc90be-d121-4602-977b-fbd0f9432052.png)

**Comment by shridarpatil** [comment]
What is the status of the template on Meta?

**Comment by shridarpatil** [comment]
Can you show me your `Whats Notification`?

**Comment by elmerchanquin** [comment]
This is the user test:
![image](https://user-images.githubusercontent.com/31196079/223913581-503578f3-38d9-4494-8544-41ae45de4ea0.png)
This is the first one, using the custom field:
![image](https://user-images.githubusercontent.com/31196079/223913689-89d4becc-17a4-40ad-8e39-da37f088c05c.png)

**Comment by elmerchanquin** [comment]
Don't think so.
![image](https://user-images.githubusercontent.com/31196079/223915302-5ec320b7-96b8-4b40-80cb-828a150a7aba.png)
I tried to modify the user and create a new patient appointment right now, but I haven't received any logs.

**Comment by elmerchanquin** [comment]
![Screenshot 2023-03-08 222001](https://user-images.githubusercontent.com/31196079/223916052-eebba71f-162c-485a-95e3-e439ec49236d.png)
Thats one record, but I think its from the Direct Whatsapp message.

**Comment by shridarpatil** [comment]
This is business initiated message.

**Comment by shridarpatil** [comment]
have added a fix for this. Also you need to save mobile with country code.

**Comment by elmerchanquin** [comment]
Thank you, I'll review those details and provide my feedback.
