### ISSUE TITLE
Issue with WhatsApp Integration

### ISSUE THREAD

**Issue by sadidc** [shridarpatil/frappe_whatsapp#19]
Hello Shridarpatil,

I have just implemented, frappe WhatsApp.
MY ERPNext is self hosting, V14.

I was able to integrate with Whatsapp, Settings seem to be fine, I even created template and it got approved on Meta.

However I am unable to send messages, WhatsApp notification list is also created.

One issue I am facing is that I am unable to send manual message.

Couple of screenshots for your reference.

Your support will be highly appreciated

<img width="558" alt="Screenshot 2023-03-30 at 1 17 49 PM" src="https://user-images.githubusercontent.com/34000901/228791160-fa3966b0-f69f-4d11-8eb6-d4f430961e47.png">

<img width="1411" alt="Screenshot 2023-03-30 at 1 18 03 PM" src="https://user-images.githubusercontent.com/34000901/228790639-f89e8e12-ea2f-4432-a251-2e8c2595c7f8.png">

**Comment by shridarpatil** [comment]
can you show me your template and whatsapp notification?

**Comment by sadidc** [comment]
Thanks for the quick response.

FYI
<img width="1342" alt="Screenshot 2023-03-30 at 1 36 17 PM" src="https://user-images.githubusercontent.com/34000901/228795119-80964bb9-66a0-407f-b69d-78bbe52c4e96.png">
<img width="1297" alt="Screenshot 2023-03-30 at 1 36 34 PM" src="https://user-images.githubusercontent.com/34000901/228795142-43b18c88-d08d-46cb-96f5-af7a0061f658.png">

**Comment by sadidc** [comment]
I also tried changing the options on event type, no luck.
I also used user form, exactly the same way you have mentioned in the document, No Luck.

**Comment by shridarpatil** [comment]
https://github.com/shridarpatil/frappe_whatsapp#readme

**Comment by sadidc** [comment]
thank you, will work on this and connect with you. 👍

**Comment by sadidc** [comment]
Hello Shridar,

Can you let me know if the below template and notifications are set up correctly?

I also want to know why don't I have the option of sending messages manually.
<img width="984" alt="Screenshot 2023-03-30 at 2 49 46 PM" src="https://user-images.githubusercontent.com/34000901/228814000-3811c8d8-351c-46ad-8db4-360949b9a611.png">
<img width="980" alt="Screenshot 2023-03-30 at 2 51 21 PM" src="https://user-images.githubusercontent.com/34000901/228814022-34087cc2-74c1-4cef-9d8c-7d537d88482b.png">
<img width="1160" alt="Screenshot 2023-03-30 at 2 51 39 PM" src="https://user-images.githubusercontent.com/34000901/228814028-e46cd311-9fce-4ffb-961e-61250e31347c.png">

**Comment by shridarpatil** [comment]
follow the guidelines for template creation 
https://developers.facebook.com/docs/whatsapp/message-templates/guidelines/#samples
