### ISSUE TITLE
How to create action button in WhatsApp template

### ISSUE THREAD

**Issue by chechani** [shridarpatil/frappe_whatsapp#20]
How to create action button in WhatsApp template?

like book now,  call now etc

**Comment by shridarpatil** [comment]
This feature is not yet available in the app.

**Comment by chechani** [comment]
So if we create Template directly in Meta, will it fetch here?

**Comment by shridarpatil** [comment]
yes. you can sync templates from meta

**Comment by chechani** [comment]
How to sync templated from Meta.

**Comment by shridarpatil** [comment]
![image](https://user-images.githubusercontent.com/11792643/230310127-e5ebe6c5-8ffb-44dc-9253-25c3a9e362b3.png)

**Comment by chechani** [comment]
Thanks its working
