### ISSUE TITLE
Problems sending/receiving media

### ISSUE THREAD

**Issue by emanuelediluzio** [shridarpatil/frappe_whatsapp#23]
Trying to send media via frappe_whatsapp, the message is not sent the same thing goes for receiving messages, why?

**Comment by kamal-star** [comment]
SalesInvoice' object has no attribute 'get_document_share_key 
Iam getting this issue while send pdf through erpnext. how to resolve this

**Comment by shridarpatil** [comment]
you can send only pdf  as of now. Receiving media is not yet implemented

**Comment by kamal-star** [comment]
i am not able to send the media its showing get_document_share_key function not working and showing error can you help me how to resolve it
<img width="303" alt="image" src="https://github.com/shridarpatil/frappe_whatsapp/assets/92625927/cd05118a-a7ce-473a-858d-1e1f07386655">

**Comment by shridarpatil** [comment]
Which frappe version are you using? This app works with frappe 14+ version
