### ISSUE TITLE
pdf sending issue while sending it through frappe whatsapp 

### ISSUE THREAD

**Issue by kamal-star** [shridarpatil/frappe_whatsapp#24]
pdf sending issue while sending it through frappe whatsapp 
SalesInvoice' object has no attribute 'get_document_share_key

**Comment by shridarpatil** [comment]
which frappe version your using?

**Comment by kamal-star** [comment]
v14 iam using

**Comment by shridarpatil** [comment]
you need to update to 14

**Comment by kamal-star** [comment]
can you tell me how can i make it work in v13

**Comment by shridarpatil** [comment]
its not possible in v13 get_document_share_key is implemented in v14 you cannot replicate it v13

**Comment by kamal-star** [comment]
i switched it to v14 but now message is triggering perfectly but the messsage containing document is not reaching to the reciever only the text template message is recieved by reciever . Can you tell me why is that and how cam i fix it

**Comment by shridarpatil** [comment]
Check your template. It should accept media.
