### ISSUE TITLE
Does Incoming Message support file attachments also?

### ISSUE THREAD

**Issue by chechani** [shridarpatil/frappe_whatsapp#27]
Does Incoming Message support file attachments also?

**Comment by shridarpatil** [comment]
Unfortunately, Incoming Message does not support file attachments. However, I want to assure you that adding this feature is on our to-do list. While I don't have a specific estimated time for when it will be implemented

**Comment by chechani** [comment]
Thanks for replying and building this feature in the APP.

I know this is a longshot to provide ETA for this.

But can you guide to Meta documentation for this feature so that meanwhile I can build this feature externally.

**Comment by chechani** [comment]
I have successfully deployed the file attachment in incoming message, can I raise PR for same?

**Comment by shridarpatil** [comment]
Yeah you can raise the PR.

**Comment by chechani** [comment]
Hi, I have raised the PR https://github.com/shridarpatil/frappe_whatsapp/pull/32
