### ISSUE TITLE
How to use Existing templates from Meta account

### ISSUE THREAD

**Issue by chandrubiradar** [shridarpatil/frappe_whatsapp#33]
How can I use already created templates from Meta account, while creating WhatsApp templates.
Currently we need to create a new template.

Let me know if there is any method to use the existing templates

**Comment by shridarpatil** [comment]
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/11792643/db74724c-cb94-4e84-8be4-a30b2bad90a9)
you can pull your existing templated on you frappe instance and use it.

**Comment by chandrubiradar** [comment]
Thanks Shridarpatil/Frappe_whatsapp.

It worked.
