### ISSUE TITLE
Created Whatsapp template not working in Whatsapp Notification

### ISSUE THREAD

**Issue by chandrubiradar** [shridarpatil/frappe_whatsapp#35]
I have created template in meta for sending Payment receipts, So I have added PDF document as attachment in meta account.

Also the template is approved and its shown in Whatsapp templates in Frappe.

But while saving the Whatsapp Notifications, I am getting following error.

Someone please on this.
![Screenshot (37)](https://github.com/shridarpatil/frappe_whatsapp/assets/47516435/42eb3cc5-7952-4c2e-b2b9-ea9590312416)

**Comment by chandrubiradar** [comment]
I have saved by checking custom attachment and added some document , it started working fine.

Then I have enabled Attach document print again and its working fine now.

Don't know where was the issue. Anyway its working fine
Closing this issue

**Comment by shridarpatil** [comment]
you need to pull the latest code and run migrations.

**Comment by chandrubiradar** [comment]
This is working @shridarpatil 
Thanks for the information
