### ISSUE TITLE
Issue with Template Status

### ISSUE THREAD

**Issue by moizsami** [shridarpatil/frappe_whatsapp#36]
Hi,

I had created a notification template, I checked on facebook it has been approved  and is now Active as well, but on ERPNext it keeps showing as pending
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/24491918/3441f464-7105-4e45-8cef-48b3cb477a0a)

Result of this, when I try to send any notification I receive the following message
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/24491918/4cff7ae6-c566-477a-a8c9-6c05ec8533fd)

Kindly need your assistance

Approved template
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/24491918/2e3c1303-1f7f-4c0a-97e0-a581da2d85d3)

**Comment by shridarpatil** [comment]
Did you enable webhooks?

**Comment by Riadat-AlMaemura** [comment]
> Could you let me know if you enabled webhooks? The status gets updated if you have enabled webhooks. Also, the error is not related to the status, the language code is not set in the template.

i have the same issue, ihave enabeled webhooks.

**Comment by zahed-azzani** [comment]
> Could you let me know if you enabled webhooks? The status gets updated if you have enabled webhooks. Also, the error is not related to the status, the language code is not set in the template.

https://github.com/shridarpatil/frappe_whatsapp/issues/36
