### ISSUE TITLE
getting error while selecting notification type = schedule events

### ISSUE THREAD

**Issue by umarless** [shridarpatil/frappe_whatsapp#37]
When I am selecting Notification Type as Scheduled Events fields "Reference Document Type" and "Field Name" is disappearing but after saving below error is showing. 

![image](https://github.com/shridarpatil/frappe_whatsapp/assets/97974556/bba8f7c9-d059-47d8-9ebb-c31b1b3fc5ac)

We can achieve this by unchecking "Mandatory" and adding this condition **eval:doc.notification_type == "DocType Event"** to field "Mandatory Depends On" in "Reference Document Type" and "Field Name" fields from "WhatsApp Notification" doctype.

I am unable to uncheck "Mandatory" from both fields because these are standard fields.

**Comment by shridarpatil** [comment]
looks like an issue here. Will debug and fix.
