### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.facebook.com/v15.0/None/message_templates

### ISSUE THREAD

**Issue by chandrubiradar** [shridarpatil/frappe_whatsapp#4]
I tried with the URL you have provided for the WhatsApp integration.
Its throwing the error.

Please help me to solve this @shridarpatil

**Comment by shridarpatil** [comment]
You phone ID is none. I guess you missed it. Can you your whats app settings?

**Comment by chandrubiradar** [comment]
I left phone id blank.
In the URL field, i have used the same URL, which you used in the image you
shared.
It's not working

**Comment by chandrubiradar** [comment]
Which one we need to put in URL section?

**Comment by chandrubiradar** [comment]
I have added Phone ID and Business ID
Although its throwing an error.
Can you please look at below screenshot
![Screenshot (687)](https://user-images.githubusercontent.com/47516435/203459125-40e505b5-10ec-4da8-94c6-ced54a757606.png)

**Comment by chandrubiradar** [comment]
thanks
I will check

**Comment by shridarpatil** [comment]
Closing this as it is not related to the app. Feel free to open if the issue persists.

**Comment by chandrubiradar** [comment]
Ok, thanks.

**Comment by chandrubiradar** [comment]
Hey Shridarpatil/Frappe_whatsapp

I had problem with my credentials.
Now i have fixed the issue and now the eroor is solved.

But even after creating Template and adding doctype event for WhatsApp
notification. The messages are not going, and there is no logs recorded.

Can you please help me on this issue?

**Comment by shridarpatil** [comment]
What is the status of your template on Facebook dev?

**Comment by chandrubiradar** [comment]
Can you please elaborate a little.
I didn't understand what you are saying

**Comment by chandrubiradar** [comment]
Got it.
Give me a minute
I'm checking it

**Comment by chandrubiradar** [comment]
I have checked the template it's approved and credentials also correct.
But i am not getting any messages in WhatsApp.
Are there any logs, so that I can check what's the issue

**Comment by chandrubiradar** [comment]
Any update on this @shridarpatil

**Comment by shridarpatil** [comment]
If you have setup developer account credentials then you need to register your number on Facebook dev to receive message

**Comment by chandrubiradar** [comment]
Doesn't the messages are coming to numbers which has WhatsApp?

Do we need to register each number on which we need to receive the messages?

**Comment by chandrubiradar** [comment]
I have registered number from which i created developer account.
I am able to send messages from facebook dev.

But not receiving using frappe WhatsApp integration

**Comment by shridarpatil** [comment]
can you add a screenshot of your whats notification and doctype from where you're triggering this?

**Comment by chandrubiradar** [comment]
Sure
I will share it

**Comment by chandrubiradar** [comment]
![Screenshot (727)](https://user-images.githubusercontent.com/47516435/206180119-c8534e1d-16c9-42a6-94a6-cfb7e7fa3c0d.png)
![Screenshot (728)](https://user-images.githubusercontent.com/47516435/206180148-402e6653-0078-47df-a3f4-a1dee68f493b.png)

Please check

**Comment by chandrubiradar** [comment]
Did you figure it out the issue?

**Comment by dineshpanchal93** [comment]
I still have the same issue not receiving notifiction sent via WhatsApp Notification
