### ISSUE TITLE
Failed to trigger whatsapp message: (#100) Invalid parameter

### ISSUE THREAD

**Issue by ravaljay23** [shridarpatil/frappe_whatsapp#43]
From Today, It is failed to trigger whatsapp message for me

**Here is Whatsapp notification log.**
{
    "error": {
        "code": 100,
        "error_data": {
            "details": "Parameter 'text' is mandatory for component parameter type 'text'",
            "messaging_product": "whatsapp"
        },
        "fbtrace_id": "AauRgAP8m_ImekhgAZPeC7d",
        "message": "(#100) Invalid parameter",
        "type": "OAuthException"
    }
}

**Comment by shridarpatil** [comment]
can you check the request payload? Looks like the text is not sent to they api.

**Comment by ravaljay23** [comment]
Working now. there was some custom field in doctype in which the response value are "null" and it's used in Whatsapp Notification. due to that error was generated.
