### ISSUE TITLE
whats app image

### ISSUE THREAD

**Issue by QuantbitERP** [shridarpatil/frappe_whatsapp#46]
Hi
How to send image through whats app?

**Comment by shridarpatil** [comment]
Can you explain in detail what you are trying to achieve?

**Comment by QuantbitERP** [comment]
When document is save I want to send QR code through whats app. Is it Possible?

**Comment by shridarpatil** [comment]
is it a dynamic qr code?

**Comment by shridarpatil** [comment]
yes you can send. Pull the latest code i have added this in latest code
