### ISSUE TITLE
ModuleNotFoundError: No module named 'frappe_whatsapp'

### ISSUE THREAD

**Issue by bytebolt** [shridarpatil/frappe_whatsapp#49]
Hi there,
I was trying to install it with docker and managed to install it by using the given commands and could see it installed after using the following command
bench --site site_name list-apps

Somehow my site is not loading up anymore. Restating the container gives the following error
ModuleNotFoundError: No module named 'frappe_whatsapp'

Am I missing any steps?

Thanks for the help

**Comment by shridarpatil** [comment]
What are the steps you did to install the app in docker?
