### ISSUE TITLE
Notification sent successfully but not gettting any message

### ISSUE THREAD

**Issue by nilpatel42** [shridarpatil/frappe_whatsapp#50]
- I have done Whatsapp Setting
- Template is Approved
- but Whatsapp Notification give this error
- i can send massage via Whatsapp Message but i can send in text only, not with attachment
- how to configure received message

**Comment by shridarpatil** [comment]
did you send message using template?

**Comment by nilpatel42** [comment]
sorry to disturb you, now its working, i think it take some time to after installation
two question is still 
without ssl certificate incoming message not working ?
and permanent token is not accepting by the whatsapp setting 

thank you for your reply

**Comment by nilpatel42** [comment]
i get this error in whatsapp message when i use permanent token 

![image](https://github.com/shridarpatil/frappe_whatsapp/assets/135511086/d727b169-3196-4b36-854c-d7a301fd2879)
