### ISSUE TITLE
Messages are not getting send

### ISSUE THREAD

**Issue by Suraj787** [shridarpatil/frappe_whatsapp#57]
i have generated  token temp setting looks something like below
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/25462611/cf68fd31-a063-4418-9919-903d39278bb9)
Certainly, here's a rephrased version of your statement:

I'm attempting to send messages upon creating a record, and although the record is saved and the status changes to success, I'm not receiving any messages. Do you have any suspicions about potential issues or anything unusual in this scenario? How can I go about debugging this situation? The phone number has already been added. My ERPNext instance is version 13, set up as a multitenant DNS-based system with SSL.
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/25462611/3f23dbb3-4e26-4f70-830e-c6a5dbab160d)

**Comment by simran-baliyan** [comment]
I am also facing same issue. @shridarpatil , could you fix it please?

**Comment by shridarpatil** [comment]
@Suraj787 @simran-baliyan you cannot send direct message unless you receive  the 1st message.

**Comment by simran-baliyan** [comment]
@Suraj787 , For example, customer placed an order on Webshop and I want that he should get notification about his order on Whatsapp. Can't a system send notifications?

**Comment by Suraj787** [comment]
@simran-baliyan  Certainly, we can send the notification. The only requirement is that the customer must have sent you the message first. I've integrated this functionality using the Gallabox API. I'm currently trying this project, but by making a slight configuration adjustment (setting notifications on sales order submission), I believe we can achieve it.

**Comment by simran-baliyan** [comment]
@Suraj787 Well that isn't practical! Could you come up with a better version of the module which can trigger notifications?

**Comment by shridarpatil** [comment]
@simran-baliyan you can do it via template and what’s app notifications. Create a template and set an event in WhatsApp notifications for sales order this will trigger what’s app message. For sending template you don’t need to receive 1st message from client.

**Comment by simran-baliyan** [comment]
@shridarpatil Okay , I see.  Do you have steps how to achive this? . I had tried it , basically , I want to send something like this:-
Hi {#var#}, Your order #{#var#} is received! 

How can I get customer name and Sales Order ID? Basically , how to configure this all?

**Comment by shridarpatil** [comment]
In WhatsApp notification you have option to add fields you can go through that once you will get a clear picture.

**Comment by simran-baliyan** [comment]
Sorry , had to uninstall this. Will wait for frappe to update WABA module.

**Comment by elbeicktalat** [comment]
I have defined various templates on Meta and everything is ok, the only issue is that I'm not able to to send an attachment even with "Attach Document Print" tick on in WhatsApp Notification.

The thing is if I take a look on the WhatsApp message from the list I can see my pdf path.

<img width="983" alt="image" src="https://github.com/shridarpatil/frappe_whatsapp/assets/59793332/c363b3d0-402c-4655-8d63-fc14427ad996">
<img width="998" alt="image" src="https://github.com/shridarpatil/frappe_whatsapp/assets/59793332/80d9b46d-0ecd-4a25-a340-814086c58463">


Any idea?

**Comment by shridarpatil** [comment]
you are using prod credentials or dev?
