### ISSUE TITLE
How can I trigger a WhatsApp Notification?

### ISSUE THREAD

**Issue by ahassoun** [shridarpatil/frappe_whatsapp#59]
Hello!

I have a WhatsApp Template, Approved, and pulled successfully. AFAIK, the only way to initiate a message from this app is via `WhatsApp Notification` DocType.

The `DocType Event` menu does not have what I need. I need a custom event.

More specifically, I have a custom button on a DocType Form View, and I need the notification to be triggered once the button is clicked.

Could you please give me high level directions on how to achive this?

BR

**Comment by simran-baliyan** [comment]
+1

**Comment by shridarpatil** [comment]
@ahassoun 
On click on button you can call an api with below snippet 
In you python code you can add the below snippet
```
doc = frappe.get_doc("<doctype name>", "<name>")
frappe.get_doc(
                "WhatsApp Notification",
                notification_name
            ).send_template_message(doc)
```

**Comment by Ulter52** [comment]
@shridarpatil 
Sir, as you said its not working for me. I am getting an error "_get_value() missing 1 required positional argument: 'fieldname'_ " .
I have custom button "Send Invoice" in doc Sales Invoice. Can you help me with this error. I am using the following code.

```
frappe.ui.form.on('Sales Invoice', {
	refresh(frm) {
		frm.add_custom_button(__('Send Invoice'), function(){
		    doc = frappe.get_doc('Sales Invoice', name);
		    frappe.get_doc(
		        'WhatsApp Notification',
		        //notification_name
                            WN-0001
		         ).send_scheduled_message(doc);
            }, "Send WhatsApp Alert");
            
	}
});
```

**Comment by Ulter52** [comment]
@ahassoun can you share me code to which doctype you implemented?

**Comment by Ulter52** [comment]
**In Client Script** 
I replaced `method: your_app_path.your_module_name.your_method` with `method:"erpnext.accounts.doctype.sales_invoice.sales_invoice.send_whatsapp_invoice",` 
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/36833512/444f58bb-52f4-4ab7-ac7a-8d83709a4083)

**In server script**
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/36833512/ea04c867-a587-4338-b950-6a610e7fc619)

Getting Error
`Failed to get method for command erpnext.accounts.doctype.sales_invoice.sales_invoice.send_whatsapp_invoice with module 'erpnext.accounts.doctype.sales_invoice.sales_invoice' has no attribute 'send_whatsapp_invoice'`
what am I doing wrong here? no custom app, Erpnext only.
