### ISSUE TITLE
Unable to Save whatsapp Template

### ISSUE THREAD

**Issue by singhranbir** [shridarpatil/frappe_whatsapp#7]
![Screenshot 2022-12-09 115910](https://user-images.githubusercontent.com/70106937/206639377-bf68c2c0-09c9-4f68-8eb7-242fc4a08872.png)

**Comment by shridarpatil** [comment]
can you show what data you have entered?

**Comment by singhranbir** [comment]
Suer, I am trying to save this

![Screenshot 2022-12-09 115910](https://user-images.githubusercontent.com/70106937/206642239-89573ded-c362-49cd-bf47-f14e5d78a0a5.png)

**Comment by singhranbir** [comment]
sure, i am trying to save this

![Screenshot 2022-12-09 121814](https://user-images.githubusercontent.com/70106937/206642372-576fd0da-d6c2-4364-89f8-f9a771cd7348.png)

**Comment by shridarpatil** [comment]
Try changing language to English (United States)

**Comment by shridarpatil** [comment]
looks like you have entered wrong url

**Comment by singhranbir** [comment]
> Try changing language to English (United States)

ok

**Comment by singhranbir** [comment]
i am testing on IP, is that okay ?
does it required a Secured Site ?

**Comment by shridarpatil** [comment]
Yeah, it's absolutely fine. You can test it anywhere

**Comment by singhranbir** [comment]
Can you please help, i entered this in settings

![whatsapp Setting](https://user-images.githubusercontent.com/70106937/206647012-7609d343-5a73-49a6-b02e-d404d640af27.png)

**Comment by shridarpatil** [comment]
```
 settings = frappe.get_doc("WhatsApp Settings", "WhatsApp Settings")
 print(settings.get_password("token"))
```
Run this in bench console can check if the token matches with the token on meta dev

**Comment by singhranbir** [comment]
> ```
>  settings = frappe.get_doc("WhatsApp Settings", "WhatsApp Settings")
>  print(settings.get_password("token"))
> ```
> 
> Run this in bench console can check if the token matches with the token on meta dev

yes, it is matching

**Comment by singhranbir** [comment]
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/integrations/utils.py", line 21, in make_request
    frappe.flags.integration_request.raise_for_status()
      method = 'POST'
      url = 'https://graph.facebook.com/v15.0/101057792862254/message_templates'
      auth = ''
      headers = {'authorization': 'Bearer EAAJyJCs34JUBAOZCQZCfZCSmRY5OdWCFqwuvD51UL1CkQdTxDHq6PD6iilpsMnHIU79SZAnxuTOyc7JfySKUC1qjZAeSuqA6VPaAHdpHHCnJdJ1dFociHfaaBlIS28qqCIk4VPyVVBhp05kJdy3y5ZClwR8WEdbZBP3P91z3YC8UZCvOrhu8C0diibnTFSLAK9buZCDu1S3poYwZDZD', 'content-type': 'application/json'}
      data = '{"name": "test", "language": "en", "category": "TRANSACTIONAL", "components": [{"type": "BODY", "text": "test    "}]}'
      s = <requests.sessions.Session object at 0x7f279ec9a860>
      exc = HTTPError('400 Client Error: Bad Request for url: https://graph.facebook.com/v15.0/101057792862254/message_templates')
  File "env/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
      self = <Response [400]>
      http_error_msg = '400 Client Error: Bad Request for url: https://graph.facebook.com/v15.0/101057792862254/message_templates'
      reason = 'Bad Request'
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com/v15.0/101057792862254/message_templates

Getting this in Error Log

**Comment by shridarpatil** [comment]
This error is related to your meta credentials.

**Comment by shridarpatil** [comment]
Also, can you delete your previous comment? It includes your credentials.

**Comment by singhranbir** [comment]
> This error is related to your meta credentials.

Will check.

Thanks for Help.
