### ISSUE TITLE
Multilingual templates do not appear when we import templates from Meta

### ISSUE THREAD

**Issue by zahed-azzani** [shridarpatil/frappe_whatsapp#70]
I fetched WhatsApp templates from Meta, but only one template was fetched for those with multiple languages. This is because ERPNext does not accept duplicate template names. Therefore, it is necessary to consider the language when fetchin templates.

the templates in meta 
![Screenshot (557)](https://github.com/shridarpatil/frappe_whatsapp/assets/67719467/f405ab2c-8400-4b4c-8fb9-64b46ceb8cca)

the temp in erpnext

![Screenshot (558)](https://github.com/shridarpatil/frappe_whatsapp/assets/67719467/53035dfc-2f61-46c9-952b-8e2cd4d874c0)

Upon comparison, we will also find that there is a template that was created  in ERPNext (zahed) and there are many notes on this template:

1- This template was created in erpnext and approved by Meta, but it is still pending in ERP Next.

![Screenshot (559)1](https://github.com/shridarpatil/frappe_whatsapp/assets/67719467/82041db9-747b-4a2c-a052-6edd3950a1b3)

2- This template was deleted from the ERP Next screen and was actually deleted from Meta, but it was not deleted in ERP Next.
![Screenshot (559)12](https://github.com/shridarpatil/frappe_whatsapp/assets/67719467/5593c03f-45ef-499c-8941-5bb281f8c55b)

3- I made several attempts to delete it from the list, but to no avail.

![Screenshot (560)](https://github.com/shridarpatil/frappe_whatsapp/assets/67719467/9d7c9190-af0f-4d32-a373-554e12f67386)

**Comment by shridarpatil** [comment]
added a fix for this.
