### ISSUE TITLE
 Message WhatsApp Templates None not found: and Server Error KeyError: 'error' Possible source of error: frappe_whatsapp (app), i'm getting a server error and message response when running whatsapp notification. Any help?

### ISSUE THREAD

**Issue by mullor2244** [shridarpatil/frappe_whatsapp#72]
### Discussed in https://github.com/shridarpatil/frappe_whatsapp/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **shridarpatil** December  7, 2022</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by mullor2244** [comment]
Guys this is happening to me on all notifications I create. this also prevents the system from saving my documents.

**Comment by shridarpatil** [comment]
You might have created a WhatsApp notification without selecting a template. Can you check?
