### ISSUE TITLE
Unable to receive the whatsapp message

### ISSUE THREAD

**Issue by aravindsprint** [shridarpatil/frappe_whatsapp#79]
Hi,

I am trying to send the whatsapp message manually, after saving the doc it shows the success status but the recipient didn't receive the message.

Please help me on how to solve this.

<img width="1060" alt="image" src="https://github.com/shridarpatil/frappe_whatsapp/assets/15940614/ce07a536-b543-432f-b6c3-1ac26c6693e8">

**Comment by shubhamgupta123** [comment]
+1

**Comment by aravindsprint** [comment]
It is working fine in the site which is https

**Comment by Payal-S-K** [comment]
I am facing the same issue.
