### ISSUE TITLE
DEPRECATION warning in getting app & not working after install the app to site , how to fix it?

### ISSUE THREAD

**Issue by ranjithphptech** [shridarpatil/frappe_whatsapp#85]
DEPRECATION: Legacy editable install of frappe-whatsapp==1.0.7 from file:///home/frappe/frappe/frappe-bench/apps/frappe_whatsapp (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat

python - 3.11
ERPNext: v15.31.4 (HEAD)
Frappe Framework: v15.29.0 (HEAD)
Frappe Whatsapp: vv1.0.7 (master)

**Comment by shridarpatil** [comment]
https://github.com/shridarpatil/frappe_whatsapp/pull/88 a fix for this is added
