### ISSUE TITLE
Unable to send documents/Images

### ISSUE THREAD

**Issue by ravi854** [shridarpatil/frappe_whatsapp#87]
Plain text messages are working fine
Attaching any document (.pdf) or image (.png/.jpeg) not working giving the below error.

"errors": [{"code": 131053, "title": "Media upload error", "message": "Media upload error", "error_data": {"details": "Downloading media from weblink failed with http code 503, status message Service Unavailable"}}]}]}, "field": "messages"}]}], "cmd": "frappe_whatsapp.utils.webhook.webhook"}

**Comment by shridarpatil** [comment]
Check the document which you were trying to upload. From the log, I can see meta got a 503 error for the document link.

**Comment by ravi854** [comment]
Thanks, its sorted, it was my firewall that was blocking the upload
