### ISSUE TITLE
Unable to Upload The Image and attach file

### ISSUE THREAD

**Issue by Pradip2113** [shridarpatil/frappe_whatsapp#89]
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com//v19.0/upload:MTphdHRhY2htZW50OjY5ZDA1ZjBiLTNjYTYtNDFmNC04YmUwLTY4MmEyYWM3MGVhMD9maWxlX2xlbmd0aD0zMjYzMTEmZmlsZV90eXBlPWltYWdlJTJGcG5n?sig=ARaNq9F2b7I4hCwV5bk
Possible source of error: frappe_whatsapp (app)

**Comment by shridarpatil** [comment]
You have entered wrong url there is extra ‘/‘ after facebook.com

**Comment by Pradip2113** [comment]
Correct URL but not add image

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com/v19.0/1207194474064173
Possible source of error: frappe_whatsapp (app)

**Comment by elbeicktalat** [comment]
Hello @shridarpatil 
I'm facing the exact same issues:

<img width="723" alt="image" src="https://github.com/user-attachments/assets/678f6908-889c-40a7-99fa-d9e370582b07">

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com/v20.0/None/uploads
Possible source of error: frappe_whatsapp (app)
```

Not sure why it's taking `None` in the url.

Any Idea?

Please note that I was able to send message successfully, but I'm not able to create a new template. **So the setup is correct.**

**Comment by elbeicktalat** [comment]
Fixed in My case.

I was missing to add the app ID. 😅
