### ISSUE TITLE
Unable to send WhatsApp message from ERPNext

### ISSUE THREAD

**Issue by akashdubey22** [shridarpatil/frappe_whatsapp#9]
I did the following things to setup this custom app, but some setting is not right & i am unable to send message like its shown in installation guide of this page.

1. Created App in Meta website
2. Added a real number on whatsapp business.
3.  Sent test message from Meta website.
4. On ERPNext ... Entered values in Whatsapp Setting Page.
5. Created  whatsapp template in ERPNext & saved. It successfully got saved on whatsapp website too. (Although got Rejected after sometime)
6. Then tried sending message from ERPNext, as shown in this app's installation page but getting the following error ....

![image](https://user-images.githubusercontent.com/34884206/211783282-38706280-51f1-4b6b-ae9a-5231e596f657.png)

Is it something related to webhook setting or something else ?

I am not an expert so please guide with simple steps

**Comment by shridarpatil** [comment]
your template has to be approved. You cannot send message using rejected template

**Comment by shridarpatil** [comment]
closing this as it is not related to app.

**Comment by webbosolutions** [comment]
add / end of https://graph.facebook.com will be 
https://graph.facebook.com/
