### ISSUE TITLE
Whatsapp Notification Improve ID 

### ISSUE THREAD

**Issue by nilpatel42** [shridarpatil/frappe_whatsapp#95]
Currently Whatsapp Notification ID is Series, 
which is difficult to identify notification subject when there is n number of notification
ID based on Notification Name is very useful

Example : 

![image](https://github.com/user-attachments/assets/be124d87-46f7-4c72-b804-352dcfafaf7a)

**Comment by shridarpatil** [comment]
You can make the changes and send PR.
